### ISSUE TITLE
set up arduino-CI for the library

### ISSUE THREAD

**Issue by RobTillaart** [milesburton/Arduino-Temperature-Control-Library#182]
Please read - https://github.com/Arduino-CI/arduino_ci/blob/master/REFERENCE.md

- [x] add .github\workflows\arduino_test_runner.yml
- [x] add .arduino-ci.yml
- [x] add test\unit_test_01.cpp_placeholder 
- [x] rename above file to .cpp when there is a fix for https://github.com/Arduino-CI/arduino_ci/issues/251

content **.arduino-ci.yml**
```
compile:
  # Choosing to run compilation tests on 2 different Arduino platforms
  platforms:
    - uno
    - leonardo
    - due
    - zero
  # Declaring Dependent Arduino Libraries (to be installed via the Arduino Library Manager)
  libraries:
    - "OneWire"

unittest:
  # These dependent libraries will be installed
  libraries:
    - "OneWire"
    # fix the #include "util/crc16" problem here?
    
 ```
content **arduino_test_runner.yml**
```
---
name: Arduino CI

on: [push, pull_request]

jobs:
  arduino_ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Arduino-CI/action@master
          #   Arduino-CI/action@v0.1.1
```

Example content **unit_test_01.cpp** see - https://github.com/RobTillaart/DS18B20_RT/blob/master/test/unit_test_001.cpp_avr_specific
